# Generated by Django 5.0.6 on 2024-05-30 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order_Details',
            new_name='Order_Detail',
        ),
    ]
